export const contentPerformanceDemo = {
  meta: {
    page: 'content_performance',
    generated_at: '2025-12-30T14:30:00Z',
    snapshot_id: 'snap_measurement_001',
    source: 'GA4 (demo)',
    boundary: 'read_only_no_feedback',
  },
  filters: {
    time_range: 'Last 30 days',
    channel: 'GA4 (demo)',
    content_id: 'All content',
  },
  kpis: {
    pageviews: 45230,
    sessions: 28350,
    engagement_rate: 0.68,
    avg_time_on_page_sec: 145,
  },
  content_rows: [
    {
      content_id: 'content_001',
      title: 'Cloud Infrastructure Guide',
      brief_id: 'brief-1',
      url_path: '/cloud-infrastructure-guide',
      sessions: 8450,
      pageviews: 12300,
      engagement_rate: 0.72,
      avg_time_on_page_sec: 180,
      last_updated: '2025-12-28T10:00:00Z',
    },
    {
      content_id: 'content_002',
      title: 'AI Automation Best Practices',
      brief_id: 'brief-3',
      url_path: '/ai-automation-best-practices',
      sessions: 6230,
      pageviews: 8900,
      engagement_rate: 0.65,
      avg_time_on_page_sec: 165,
      last_updated: '2025-12-27T14:30:00Z',
    },
    {
      content_id: 'content_003',
      title: 'llms.txt Implementation Guide',
      brief_id: 'brief-2',
      url_path: '/llms-txt-implementation',
      sessions: 5120,
      pageviews: 7200,
      engagement_rate: 0.58,
      avg_time_on_page_sec: 120,
      last_updated: '2025-12-26T09:15:00Z',
    },
    {
      content_id: 'content_004',
      title: 'Cloud Security Fundamentals',
      brief_id: 'brief-1',
      url_path: '/cloud-security-fundamentals',
      sessions: 4850,
      pageviews: 6800,
      engagement_rate: 0.71,
      avg_time_on_page_sec: 195,
      last_updated: '2025-12-25T16:45:00Z',
    },
    {
      content_id: 'content_005',
      title: 'Infrastructure Comparison',
      brief_id: 'brief-1',
      url_path: '/infrastructure-comparison',
      sessions: 3700,
      pageviews: 5030,
      engagement_rate: 0.63,
      avg_time_on_page_sec: 150,
      last_updated: '2025-12-24T11:20:00Z',
    },
  ],
  notes: [
    'Data is read-only and does not feed back into strategy, decisions, or briefs.',
    'Engagement rate calculated as (engaged sessions / total sessions).',
  ],
};

