'use client';

import { competitorIntelligenceDemo } from '@/lib/demo/geo-os/competitor-intelligence';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { DriverChip } from '@/components/geo/DriverChip';
import { MetricChip } from '@/components/geo/MetricChip';
import { GapKey } from '@/lib/geo/driverDefinitions';
import { GeoGlobalFilters } from '@/components/geo/GeoGlobalFilters';

export default function CompetitorIntelligencePage() {
  const data = competitorIntelligenceDemo;

  return (
    <TooltipProvider>
      <div className="container mx-auto p-6 space-y-6">
        <div>
          <h1 className="text-3xl font-bold">Competitor Intelligence</h1>
          <p className="text-muted-foreground mt-2">
            Competitive landscape analysis and brand positioning
          </p>
          <div className="mt-2 text-xs text-muted-foreground">
            Generated by {data.meta.source_agent} at {new Date(data.meta.generated_at).toLocaleString()}
          </div>
        </div>

        <GeoGlobalFilters />

        <div className="rounded-lg border bg-muted/50 p-4">
          <p className="text-sm text-muted-foreground">
            <strong>Read-only view:</strong> Competitive intelligence for analysis only. No execution actions available.
          </p>
        </div>

        <div className="rounded-lg border bg-card p-6">
          <h3 className="text-lg font-semibold mb-4">Primary Brand Position</h3>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-medium">{data.competitive_landscape.primary_brand.brand_name}</span>
              <div className="flex items-center gap-4">
                <span className="text-2xl font-bold">{data.competitive_landscape.primary_brand.overall_geo_score}%</span>
                <span className="text-sm text-muted-foreground capitalize">
                  {data.competitive_landscape.primary_brand.market_position}
                </span>
              </div>
            </div>
          </div>
        </div>

        <div className="rounded-lg border bg-card p-6">
          <h3 className="text-lg font-semibold mb-4">Competitors</h3>
          <div className="space-y-4">
            {data.competitive_landscape.competitors.map((competitor) => (
              <div key={competitor.brand_id} className="p-4 border rounded-lg">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <div className="font-medium">{competitor.brand_name}</div>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-sm text-muted-foreground">
                        Rank #{competitor.rank} • GEO Score: {competitor.geo_score}%
                      </span>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <button
                            type="button"
                            className="inline-flex items-center justify-center w-4 h-4 rounded-full text-muted-foreground hover:text-foreground transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                            aria-label="GEO Score information"
                          >
                            <span className="text-xs leading-none">ⓘ</span>
                          </button>
                        </TooltipTrigger>
                        <TooltipContent side="top" className="max-w-xs">
                          <p>Same scoring scale as GEO Overview.</p>
                        </TooltipContent>
                      </Tooltip>
                    </div>
                  </div>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-3">
                  <div>
                    <div className="text-xs font-medium text-muted-foreground mb-2">Strengths</div>
                    <ul className="text-sm space-y-1.5">
                      {competitor.strengths.map((s, i) => (
                        <li key={i} className="flex items-start gap-2 text-green-700">
                          <span className="mt-0.5">•</span>
                          <span>{s}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <div className="text-xs font-medium text-muted-foreground mb-2">Weaknesses</div>
                    <ul className="text-sm space-y-1.5">
                      {competitor.weaknesses.map((w, i) => (
                        <li key={i} className="flex items-start gap-2 text-orange-700">
                          <span className="mt-0.5">•</span>
                          <span>{w}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
                <div className="mt-3 pt-3 border-t">
                  <p className="text-xs text-muted-foreground">
                    Derived from AI answer analysis (snapshot-based).
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-lg border bg-card p-6">
          <div className="mb-4">
            <h3 className="text-lg font-semibold mb-2">Competitive Gaps</h3>
            <p className="text-xs text-muted-foreground">
              Topic-level deltas based on AI answer signals. Read-only guidance.
            </p>
          </div>
          <div className="space-y-4">
            {data.competitive_landscape.competitive_gaps.map((gap, i) => {
              // Map signal string to GapKey
              const getGapKey = (signal: string): GapKey | null => {
                const signalLower = signal.toLowerCase();
                if (signalLower.includes('reach')) {
                  return 'reach_gap';
                }
                if (signalLower.includes('position')) {
                  return 'position_gap';
                }
                if (signalLower.includes('sentiment')) {
                  return 'sentiment_gap';
                }
                if (signalLower.includes('visibility')) {
                  return 'visibility_gap';
                }
                return null;
              };

              return (
                <div key={gap.topic_id || i} className="p-4 border rounded-lg">
                  <div className="mb-3">
                    <div className="font-medium text-base mb-1">{gap.topic_name}</div>
                    <div className="text-sm font-medium text-foreground mt-2">
                      {gap.gap_statement}
                    </div>
                  </div>
                  
                  {/* Why it matters and Focus callouts - responsive grid */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-4">
                    {/* Why it matters callout */}
                    <div className="rounded-md border-l-2 border-blue-200 bg-blue-50/30 dark:bg-blue-950/20 p-3">
                      <div className="flex items-start gap-2">
                        <span className="text-sm mt-0.5">ℹ️</span>
                        <div className="flex-1">
                          <div className="text-xs font-bold text-foreground mb-1">Why it matters</div>
                          <p className="text-sm text-muted-foreground">{gap.why_it_matters}</p>
                        </div>
                      </div>
                    </div>
                    
                    {/* Focus callout */}
                    <div className="rounded-md border-l-2 border-primary bg-primary/5 p-3">
                      <div className="flex items-start gap-2">
                        <span className="text-sm mt-0.5">🎯</span>
                        <div className="flex-1">
                          <div className="text-xs font-bold text-foreground mb-1">Focus</div>
                          <p className="text-sm text-foreground">{gap.focus}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  {/* Signal chips with tooltips */}
                  {gap.signals && gap.signals.length > 0 && (
                    <div className="mt-4 pt-3 border-t">
                      <div className="flex flex-wrap gap-2">
                        {gap.signals.map((signal, idx) => {
                          const gapKey = getGapKey(signal);
                          if (!gapKey) return null;

                          // Map GapKey to MetricId
                          const metricIdMap: Record<GapKey, string> = {
                            reach_gap: "reachGap",
                            position_gap: "positionGap",
                            sentiment_gap: "sentimentGap",
                            visibility_gap: "visibilityGap",
                          };
                          const metricId = metricIdMap[gapKey] as any;

                          return (
                            <MetricChip
                              key={idx}
                              metricId={metricId}
                              mode="gap"
                              variant="ghost"
                              size="sm"
                            />
                          );
                        })}
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </TooltipProvider>
  );
}
